Repository ropensci/drake, pull requests merged in 2018-08, with the labels that each got.

#493 Construct a call to drake_plan() from a workflow plan data frame
  NAMESPACE
  R/drake_plan.R
  R/package.R
  R/utils.R
  man/analysis_wildcard.Rd
  man/bind_plans.Rd
  man/dataset_wildcard.Rd
  man/drake_plan.Rd
  man/evaluate_plan.Rd
  man/expand_plan.Rd
  man/file_in.Rd
  man/file_out.Rd
  man/gather_plan.Rd
  man/ignore.Rd
  man/knitr_in.Rd
  man/plan_analyses.Rd
  man/plan_summaries.Rd
  man/reduce_plan.Rd
  man/target.Rd
  tests/testthat/test-plan.R
Labels: difficulty: easy :beginner:, topic: style :barber:

#494 Use an S3 "drake_plan" class
  NAMESPACE
  R/drake_plan.R
  R/drake_plan_class.R
  R/drake_plan_print.R
  R/generate_plans.R
  R/mtcars_example.R
  R/package.R
  R/sanitize.R
  man/as_drake_plan.Rd
  tests/testthat/test-plan.R
Labels: topic: style :barber:

#502 Fixes issue where a misspelled target name would loadd all targets
  NEWS.md
  R/read.R
  tests/testthat/test-mtcars-example.R
Labels: BUG :bug:

#505 Turn R scripts and dynamic reports into drake plans
  .travis.yml
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/code_to_plan.R
  _pkgdown.yml
  man/code_to_plan.Rd
  pkgdown.sh
  tests/testthat/test-plans.R
Labels: topic: API :door:

#501 Proper clustermq parallelism
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/clustermq.R
  R/mclapply.R
  R/parallel.R
  R/parallel_ui.R
  R/priority_queue.R
  R/staged.R
  inst/testing/scenarios.csv
  man/cmq_build.Rd
  man/cmq_staged_build.Rd
  tests/testthat/test-clustermq.R
Labels: topic: performance :checkered_flag:, type: new feature :seedling:

#506 Refactor build_drake_graph()
  R/build_drake_graph.R
  R/cache_namespaces.R
  R/color.R
  R/console.R
Labels: topic: style :barber:

#507 pseudo-memoize the preprocessing steps
  NEWS.md
  R/build_drake_graph.R
  R/cache.R
  tests/testthat/test-mtcars-example.R
Labels: topic: performance :checkered_flag:, type: new feature :seedling:

#509 Avoid serialization where possible
  NEWS.md
  R/dependencies.R
  R/generate_plans.R
  R/knitr.R
  R/mc_utils.R
  R/meta.R
  R/random.R
  R/timestamp.R
  tests/testthat/test-intermediate-file.R
  tests/testthat/test-mtcars-example.R
  tests/testthat/test-random.R
Labels: topic: performance :checkered_flag:

#510 PR 2: make dependency_profile() more informative
  NEWS.md
  R/dependencies.R
  R/meta.R
  man/dependency_profile.Rd
  tests/testthat/test-cache.R
  tests/testthat/test-dependencies.R
  tests/testthat/test-mtcars-example.R
  tests/testthat/test-plans.R
Labels: topic: API :door:, topic: reproducibility :recycle:
