Repository ropensci/drake, pull requests merged in 2018-12, with the labels that each got.

#594 Move dplyr and tidyselect to "Suggests"
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/Makefile.R
  R/build.R
  R/build_times.R
  R/cache_log.R
  R/clean.R
  R/code_to_plan.R
  R/create_drake_graph.R
  R/deprecate.R
  R/drake_debug.R
  R/drake_plan.R
  R/drake_plan_source.R
  R/envir.R
  R/handlers.R
  R/knitr.R
  R/map_reduce.R
  R/package.R
  R/predict_runtime.R
  R/priority_queue.R
  R/read.R
  R/run.R
  R/test.R
  R/tidyselect_reexport.R
  R/utils.R
  R/wildcards.R
  R/withr.R
  codemeta.json
  man/build_times.Rd
  man/clean.Rd
  man/gather_by.Rd
  man/readd.Rd
  man/reduce_by.Rd
  man/reexports.Rd
  tests/scenarios/one.R
  tests/testthat/test-cache.R
  tests/testthat/test-dependencies.R
  tests/testthat/test-examples.R
  tests/testthat/test-graph.R
  tests/testthat/test-map-reduce.R
  tests/testthat/test-parallel.R
  tests/testthat/test-plans.R
  tests/testthat/test-priority-queue.R
Labels: topic: dependencies :package:

#599 597
  NEWS.md
  R/clustermq.R
  R/future.R
  R/mc_utils.R
  R/predict_runtime.R
  R/priority_queue.R
  man/predict_load_balancing.Rd
  man/predict_runtime.Rd
  tests/testthat/test-time.R
Labels: topic: dependencies :package:, topic: performance :checkered_flag:, topic: style :barber:

#601 Use `methods` reference classes instead of R6
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/package.R
  R/predict_runtime.R
  R/priority_queue.R
  man/drake_config.Rd
  man/make.Rd
  tests/testthat/test-priority-queue.R
Labels: topic: dependencies :package:

#596 Depurrr
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/code_to_plan.R
  R/create_drake_layout.R
  R/dependencies.R
  R/diagnose.R
  R/drake_plan.R
  R/drake_plan_source.R
  R/map_reduce.R
  R/package.R
  R/utils.R
  codemeta.json
  man/diagnose.Rd
  man/map_plan.Rd
  tests/testthat/test-plans.R
  tests/testthat/test-utils.R
Labels: topic: dependencies :package:

#610 Prework for faster code analysis
  NEWS.md
  R/code_analysis.R
  R/create_drake_layout.R
  R/dependencies.R
  R/hash_table.R
  tests/testthat/test-dependencies.R
  tests/testthat/test-hash-table.R
Labels: topic: performance :checkered_flag:

#612 Make bind_plans() work with lists of data frames.
  NEWS.md
  R/drake_plan.R
  tests/testthat/test-plans.R
Labels: BUG :bug:, difficulty: easy :beginner:, topic: API :door:

#620 Do not modify config$envir during make()
  NEWS.md
  R/build.R
  R/clustermq.R
  R/config.R
  R/create_drake_layout.R
  R/distributed.R
  R/drake_debug.R
  R/drake_graph_info_utils.R
  R/envir.R
  R/future.R
  R/hasty.R
  R/make.R
  R/meta.R
  R/run.R
  R/session.R
  R/test.R
  R/triggers.R
  man/drake_build.Rd
  man/drake_debug.Rd
  man/drake_future_task.Rd
  tests/testthat/test-envir.R
  tests/testthat/test-lazy-load.R
  tests/testthat/test-other-features.R
Labels: high priority :grey_exclamation:, topic: reproducibility :recycle:

#618 Untibble
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/cache_log.R
  R/code_to_plan.R
  R/create_drake_graph.R
  R/dependencies.R
  R/drake_graph_info_utils.R
  R/drake_plan.R
  R/map_reduce.R
  R/package.R
  R/utils.R
  codemeta.json
  man/map_plan.Rd
  tests/testthat/test-map-reduce.R
  tests/testthat/test-plans.R
  tests/testthat/test-utils.R
  tests/testthat/test-wildcards.R
Labels: high priority :grey_exclamation:, topic: dependencies :package:

#625 Code analysis without codetools
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/code_analysis.R
  R/code_analysis_symbols.R
  R/codetools.R
  R/hash_table.R
  R/package.R
  README.Rmd
  README.md
  inst/WORDLIST
  tests/testthat/test-code-analysis.R
  tests/testthat/test-dependencies.R
  tests/testthat/test-hash-table.R
Labels: difficulty: hard :fire:, topic: dependencies :package:

#626 Make more use of hash tables in the code analysis
  R/code_analysis.R
  R/code_analysis_symbols.R
  R/code_analysis_utils.R
  R/hash_table.R
  R/knitr.R
  R/utils.R
  tests/testthat/test-code-analysis.R
  tests/testthat/test-expose-imports.R
  tests/testthat/test-hash-table.R
  tests/testthat/test-knitr.R
  tests/testthat/test-plans.R
Labels: topic: performance :checkered_flag:

#633 Use manual base 64 encoding, file paths only.
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/build.R
  R/build_times.R
  R/cache.R
  R/cache_ui.R
  R/check.R
  R/code_analysis_utils.R
  R/compatibility.R
  R/console.R
  R/dependencies.R
  R/diagnose.R
  R/drake_graph_info_utils.R
  R/encoding.R
  R/future.R
  R/handlers.R
  R/igraph_utils.R
  R/knitr.R
  R/memory.R
  R/meta.R
  R/outdated.R
  R/package.R
  R/path_encoding.R
  R/predict_runtime.R
  R/read.R
  R/sanitize.R
  R/strings.R
  R/subspace.R
  R/utils.R
  R/whole_static_analysis.R
  man/build_times.Rd
  man/file_store.Rd
  man/knitr_deps.Rd
  tests/testthat/test-cache.R
  tests/testthat/test-dependencies.R
  tests/testthat/test-deprecate.R
  tests/testthat/test-edge-cases.R
  tests/testthat/test-graph.R
  tests/testthat/test-knitr.R
  tests/testthat/test-other-features.R
  tests/testthat/test-plans.R
  tests/testthat/test-strings.R
  tests/testthat/test-time.R
  tests/testthat/test-triggers.R
Labels: difficulty: hard :fire:, topic: performance :checkered_flag:
